Switch from Terraform to OpenTofu  (#2)
* Switch from Terraform to OpenTofu per skyscrapers/platform#1174

* Fix terraform command in docker build

diff --git a/scripts/docker-build b/scripts/docker-build
--- a/scripts/docker-build
+++ b/scripts/docker-build
@@ -17,7 +17,7 @@ USAGE:
     $0 <MANDATORY ARGUMENTS> [OPTIONAL ARGUMENTS]
 MANDATORY ARGUMENTS:
     --image-name <name>        Name of the Docker image you'd like to build, e.g. ljfranklin/terraform-resource:PR-test
-    --terraform-url <url>      URL of the terraform release you'd like to include, e.g. https://releases.hashicorp.com/terraform/0.9.3/terraform_0.9.3_linux_amd64.zip
+    --opentofu-url <url>       URL of the opentofu release you'd like to include, e.g. https://github.com/opentofu/opentofu/releases/download/v1.7.1/tofu_1.7.1_linux_amd64.zip
     --terragrunt-url <url>      URL of the terragrunt release you'd like to include, e.g. https://github.com/gruntwork-io/terragrunt/releases/download/v0.43.0/terragrunt_linux_amd64
     --target-arch <arch>       Architecture to build the image for e.g. amd64 or arm64
 OPTIONAL ARGUMENTS:
@@ -48,12 +48,12 @@ while true ; do
       image_name="$2"
       shift 2
       ;;
-    --terraform-url)
+    --opentofu-url)
       if [ -z "$2" ]; then
-        >&2 echo -e "${red}--terraform-url requires an argument!${nc}"
+        >&2 echo -e "${red}--opentofu-url requires an argument!${nc}"
         exit 1
       fi
-      terraform_url="$2"
+      opentofu_url="$2"
       shift 2
       ;;
     --terragrunt-url)
@@ -87,8 +87,8 @@ if [ -z "${image_name}" ]; then
   >&2 echo -e "${red}Missing required flag --image-name <name>!${nc}"
   usage
 fi
-if [ -z "${terraform_url}" ]; then
-  >&2 echo -e "${red}Missing required flag --terraform-url <url>!${nc}"
+if [ -z "${opentofu_url}" ]; then
+  >&2 echo -e "${red}Missing required flag --opentofu-url <url>!${nc}"
   usage
 fi
 if [ -z "${terragrunt_url}" ]; then
@@ -101,16 +101,16 @@ trap "{ rm -rf ${tmpdir}; }" EXIT
 
 pushd "${tmpdir}" > /dev/null
 
-  echo "Downloading terraform from '${terraform_url}'..."
-  wget -q -O terraform.zip "${terraform_url}"
-  mkdir -p ./amd64/terraform
-  unzip -d ./amd64/terraform terraform.zip > /dev/null
+  echo "Downloading OpenTofu from '${opentofu_url}'..."
+  wget -q -O opentofu.zip "${opentofu_url}"
+  mkdir -p ./amd64/terraform/opentofu
+  unzip -d ./amd64/terraform/opentofu opentofu.zip > /dev/null
 
   echo "Downloading terragrunt from '${terragrunt_url}'..."
   wget -q -O ./amd64/terraform/terragrunt "${terragrunt_url}"
   chmod +x ./amd64/terraform/terragrunt
 
-  echo "Compiling terraform-resource binaries..."
+  echo "Compiling terragrunt-resource binaries..."
   CGO_ENABLED=0 GOOS=linux GOARCH=amd64 "${release_dir}/scripts/build" "$PWD/amd64" > /dev/null
 
   echo "Building docker image '${image_name}'..."
